"""Prompt templates and generation modules."""
from .prompts import (
    RESUME_PARSER_SYSTEM_PROMPT,
    RESUME_PARSER_USER_PROMPT,
    CV_IMPROVEMENT_SYSTEM_PROMPT,
    CV_IMPROVEMENT_USER_PROMPT,
    CAREER_MENTOR_SYSTEM_PROMPT,
    CAREER_MENTOR_RAG_PROMPT,
    GUARDRAILS_CLASSIFIER_PROMPT,
)

__all__ = [
    "RESUME_PARSER_SYSTEM_PROMPT",
    "RESUME_PARSER_USER_PROMPT",
    "CV_IMPROVEMENT_SYSTEM_PROMPT",
    "CV_IMPROVEMENT_USER_PROMPT",
    "CAREER_MENTOR_SYSTEM_PROMPT",
    "CAREER_MENTOR_RAG_PROMPT",
    "GUARDRAILS_CLASSIFIER_PROMPT",
]
